spring.application.name=StockService

server.port=8083

# PostgreSQL - employeeDb
spring.datasource.url=jdbc:postgresql://localhost:5432/EmployeeDB
spring.datasource.username=postgres
spring.datasource.password=tiger
spring.datasource.driver-class-name=org.postgresql.Driver
eureka.instance.hostname=localhost
eureka.instance.prefer-ip-address=true
# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka