spring.application.name=EurekaServer
server.port=8761

# Server khud register nahi karega
eureka.client.register-with-eureka=false

# Server khud registry fetch nahi karega
eureka.client.fetch-registry=false